# Generated by Django 2.2.3 on 2019-09-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarbCount', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practitioner',
            name='user',
        ),
    ]
