# Generated by Django 2.2.3 on 2019-09-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarbCount', '0003_remove_practitioner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diabetic',
            name='user',
        ),
    ]
